const ExceptionMessage = {
  USER_ROLE: 'This type of user not able to do this',
  USER_ROLE_NOT_ADD: 'User type not specified for access',
  USER_EXISTS: 'Account with this email already exists.',
  UNAUTHORIZED_USER: 'Unauthorized user.',
  INCORRECT_CREDENTIALS:
    'Your authentication information is incorrect. Please try again.',
  INCORRECT_EMAIL:
    'Account with that email does not exist. Try again or create a new account.',
  INCORRECT_TENANT_NAME: 'Account with that tenant name does not exist.',
  TENANT_EXISTS: 'Tenant does not is exists',
  TENANT_NAME_EXISTS: 'Tenant with this name already exists',
  INCORRECT_WORKER_NAME:
    'Account with that worker name does not exist. Try again or create a new account.',
  INVALID_TOKEN: 'Token is invalid.',
  PASSWORDS_NOT_MATCH: 'Passwords do not match.',
  WORKER_NAME_EXISTS: 'Worker with this name is exist',
  WORKER_NOT_FOUND: 'Worker not Found',
  MASTER_NOT_FOUND: 'Master not Found',
  SPACE_NOT_FOUND: 'Space not found.',
  OBJECT_NOT_FOUND: 'Object not found, reload page and try again',
  FUNCTION_NAME_EXISTS: 'Function with this name already exists.',
  FUNCTION_NOT_CREATED: 'Something went wrong and function don`t created.',
  FUNCTION_NOT_FOUND: 'Function not found.',
  FUNCTION_NOT_CHANGE: 'Function code no changes.',
  FUNCTION_NOT_UPDATED: 'Function code not updated.',
  GROUP_NOT_SELECTED: 'Please select any group or create a new one first',
  GROUP_NOT_EMPTY: 'The group with workers can not be deleted',
  GROUP_NOT_FOUND: 'Group not found',
  GROUP_EXISTS: 'Group with this name already exists',
  KEY_PAIR_NOT_FOUND: 'Key pair not found',
  INSTANCE_NOT_FOUND: 'Instance not found',
  SSH_KEY_NOT_FOUND: 'Ssh key not found',
  NOTHING_TO_UPDATE: 'Nothing to update',
  FAILED_TO_CREATE: 'Failed to create instance',
  SPACE_EXISTS: 'Space with this name already exists',
  PERMISSION_LACK: 'Permissions are required to access',
  OBJECT_NOT_UPLOADED: 'Object is not uploaded',
  OBJECT_NAME_RULE: 'Object name is not correct',
  OBJECT_ACCESS_DENIED: 'You do not have access to this object',
  OPERATION_SYSTEM_NOT_FOUND: 'Operation system not found',
} as const;

export { ExceptionMessage };
